
apiVersion: v1
data:
  myorg.tmpl: >2-
      <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

        <html xmlns="http://www.w3.org/1999/xhtml" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">

        <head>

        <meta name="viewport" content="width=device-width">

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

        <title>{{ template "__subject" . }}</title>

        <style>

        @media only screen and (max-width: 640px) {
          body {
            padding: 0 !important;
          }

          h1,
        h2,

        h3,

        h4 {
            font-weight: 800 !important;
            margin: 20px 0 5px !important;
          }

          h1 {
            font-size: 22px !important;
          }

          h2 {
            font-size: 18px !important;
          }

          h3 {
            font-size: 16px !important;
          }

          .container {
            padding: 0 !important;
            width: 100% !important;
          }

          .content {
            padding: 0 !important;
          }

          .content-wrap {
            padding: 10px !important;
          }

          .invoice {
            width: 100% !important;
          }
        }

        </style>

        </head>


        <body itemscope itemtype="http://schema.org/EmailMessage" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; height: 100%; line-height: 1.6em; background-color: #f6f6f6; width: 100%;">


        <table class="body-wrap" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; background-color: #f6f6f6; width: 100%;" bgcolor="#f6f6f6">
          <tr style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
            <td style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; vertical-align: top;"></td>
            <td class="container" width="600" style="font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; vertical-align: top; display: block; max-width: 600px; margin: 0 auto; clear: both;" valign="top">
              <div class="content" style="font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; max-width: 600px; margin: 0 auto; display: block; padding: 20px;">
                <table class="main" width="100%" cellpadding="0" cellspacing="0" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; background-color: #fff; border: 1px solid #e9e9e9; border-radius: 3px;" bgcolor="#fff">
                  <tr style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                    {{ range .Alerts }}
                      {{ if eq .Labels.severity "Critical" }}
                        <td style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; vertical-align: top; font-size: 16px; color: #fff; font-weight: 500; padding: 20px; text-align: center; border-radius: 3px 3px 0 0; background-color: #e02f2f;" valign="top" align="center" >
                           <h3 style="color: white; font-size: 25px; font-weight:bolder"> Severity : {{ .Labels.severity }} </h3>
                        </td>
                      {{ else if eq .Labels.severity "High" }}
                          <td style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; vertical-align: top; font-size: 16px; color: #fff; font-weight: 500; padding: 20px; text-align: center; border-radius: 3px 3px 0 0; background-color: #F88017;" valign="top" align="center">
                             <h3 style="color: white; font-size: 25px; font-weight:bolder"> Severity : {{ .Labels.severity }} </h3>
                          </td>
                      {{ else }} 
                          <td style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; vertical-align: top; font-size: 16px; color: #fff; font-weight: 500; padding: 20px; text-align: center; border-radius: 3px 3px 0 0; background-color: #ffe433;" valign="top" align="center">
                            <h3 style="color: black; font-size: 25px; font-weight:bolder"> Severity : {{ .Labels.severity }} </h3>
                          </td>
                      {{ end }}
                    {{ end }}
                  </tr>

                  <tr style=" margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                    <td class="content-wrap" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; vertical-align: top; padding: 30px;" valign="top">
                      <table width="100%" cellpadding="0" cellspacing="0"  style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                        <tr style=" margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                          <td class="content-block" style= " font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; vertical-align: middle; text-align: center; padding: 0 0 20px;" ; colspan="3"; >
                            <a href="{{ .CommonAnnotations.fightingstepslink }}" class="btn-primary" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; text-decoration: none; color: #FFF; background-color: #348eda; border: solid #348eda; border-width: 10px 20px; line-height: 2em; font-weight: bold; text-align: center; cursor: pointer; display: block; width: 100%;  border-radius: 5px; text-transform: capitalize; white-space: nowrap;">{{ .CommonAnnotations.firstAidButton }}</a>
                          </td>
                        </tr>
                        
                        <tr style=" margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                          
                          <td class="content-block" style="width:33.3%;  margin: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: middle; text-align: left; padding: 0 0 20px;">
                            <a href="{{ template "__alertmanagerURL" . }}" class="btn-primary" style="margin: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; text-decoration: none; color: #FFF; background-color: #348eda; border: solid #348eda; border-width: 10px 20px; line-height: 2em; font-weight: bold; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: capitalize; white-space: nowrap;">View in Alertmanager</a>
                          </td>  

                          <td class="content-block" style="width:33.3%; margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; vertical-align: middle; text-align: center; padding: 0 0 20px;">
                              <a href="{{ .CommonAnnotations.queryLink }}" class="btn-primary" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; text-decoration: none; color: #FFF; background-color: #348eda; border: solid #348eda; border-width: 10px 20px; line-height: 2em; font-weight: bold; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: capitalize; white-space: nowrap;">{{ .CommonAnnotations.queryButton }}</a>
                          </td>

                        
                       
                         <td class="content-block" style="width:33.3%;  margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; vertical-align: middle; text-align: right; padding: 0 0 20px;" >
                              <a href="<your organization ticket pid url>&issuetype=<issue type>&reporter=<your default reporter>&summary={{ .CommonAnnotations.title }}&description={{ range .GroupLabels.SortedPairs }}{{ .Name }}={{ .Value }}%0A{{ end }}%0APlease checkout this first aid document for solving this alert.%0A{{ .CommonAnnotations.fightingstepslink }}&customfield_10005=1&priority=3&duedate={{ range .Alerts }}{{ .StartsAt.Format "02/Jan/06" }}{{ end }}&labels=Incident" class="btn-primary" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; text-decoration: none; color: #FFF; background-color: #348eda; border: solid #348eda; border-width: 10px 20px; line-height: 2em; font-weight: bold; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: capitalize; white-space: nowrap;">Create Jira Issue</a>
                          </td>
                        </tr>

                        
                        <tr style=" margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                          <td class="content-block" style= " font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; vertical-align: middle; text-align: center; padding: 0 0 20px;" ; colspan="3"; >
                            <a href="https://robomq.sharepoint.com/sites/OperationsPortal/SitePages/How-to-Silence-Alerts.aspx" class="btn-primary" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; text-decoration: none; color: #FFF; background-color: #348eda; border: solid #348eda; border-width: 10px 20px; line-height: 2em; font-weight: bold; text-align: center; cursor: pointer; display: block; width: 100%;  border-radius: 5px; text-transform: capitalize; white-space: nowrap;">How to Silence Alerts?</a>
                          </td>
                        </tr>


                        {{ if gt (len .Alerts.Firing) 0 }}
                        <tr style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                          <td class="content-block" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; vertical-align: top; padding: 0 0 20px; color: #000000;" valign="top">
                            <strong style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">[{{ .Alerts.Firing | len }}] Firing</strong>
                          </td>
                        </tr>
                        {{ end }}
                        {{ range .Alerts.Firing }}
                        <tr style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                          <td colspan="3" ; class="content-block" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; vertical-align: top; padding: 0 0 20px; color: #000000;" valign="top">
                            <strong style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">Labels</strong><br style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; color: #000000;">
                            {{ range .Labels.SortedPairs }}{{ .Name }} = {{ .Value }}<br style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; color: #000000;">{{ end }}
                          </td>
                        </tr>
                        {{ end }}

                        {{ if gt (len .Alerts.Resolved) 0 }}
                          {{ if gt (len .Alerts.Firing) 0 }}
                        <tr style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                          <td class="content-block" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; vertical-align: top; padding: 0 0 20px;" valign="top">
                            <br style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                            <hr style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                            <br style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                          </td>
                        </tr>
                          {{ end }}
                        <tr style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                          <td class="content-block" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; vertical-align: top; padding: 0 0 20px;" valign="top">
                            <strong style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">[{{ .Alerts.Resolved | len }}] Resolved</strong>
                          </td>
                        </tr>
                        {{ end }}
                        {{ range .Alerts.Resolved }}
                        <tr style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                          <td class="content-block" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; vertical-align: top; padding: 0 0 20px;" valign="top">
                            <strong style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">Labels</strong><br style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                            {{ range .Labels.SortedPairs }}{{ .Name }} = {{ .Value }}<br style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">{{ end }}
                            {{ if gt (len .Annotations) 0 }}<strong style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">Annotations</strong><br style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">{{ end }}
                            {{ range .Annotations.SortedPairs }}{{ .Name }} = {{ .Value }}<br style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">{{ end }}
                            
                          </td>
                        </tr>
                        {{ end }}
                      </table>
                    </td>
                  </tr>
                  
                </table>

                <div class="footer" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; width: 100%; clear: both; color: #999; padding: 20px;">
                  <table width="100%" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                    <tr style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px;">
                      <td class="aligncenter content-block" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; vertical-align: top; padding: 0 0 20px; text-align: center; color: #999; font-size: 12px;" valign="top" align="center"><a href="{{ .ExternalURL }}" style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; text-decoration: underline; color: #999; font-size: 12px;">Sent by {{ template "__alertmanager" . }}</a></td>
                    </tr>
                  </table>
                </div></div>
            </td>
            <td style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'; box-sizing: border-box; font-size: 14px; vertical-align: top;" valign="top"></td>
          </tr>
        </table>


        </body>

        </html>
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-15.9.0
    component: alertmanager
    heritage: Helm
    release: monitoring
  name: myorg-tmpl
  namespace: default
